ci: update release publish job

diff --git a/.github/workflows/github-packages-publish.yml b/.github/workflows/github-packages-publish.yml
--- a/.github/workflows/github-packages-publish.yml
+++ b/.github/workflows/github-packages-publish.yml
@@ -64,8 +64,8 @@ jobs:
           # Update version in package.json and package-lock.json without creating a git tag
           version_label="$(echo "${LABEL_NAME}" | cut -d'/' -f2)"
           # Check if the version label is one of the expected types
-          if [[ ! "$version_label" =~ ^(patch|minor|major|prepatch|preminor|premajor)$ ]]; then
-            echo "Error: Invalid version label '$version_label'."
+          if [[ ! "$version_label" =~ ^(patch|minor|major)$ ]]; then
+            echo "Error: Invalid version label '$version_label'. Valid labels are 'release/patch', 'release/minor', and 'release/major'. Please use one of these labels to trigger version updates."
             exit 1
           fi
           echo "Bumping version to $version_label"
@@ -77,7 +77,7 @@ jobs:
         env:
           LABEL_NAME: ${{ github.event.label.name }}
 
-  pr-merge-publish:
+  publish-release-package:
     if: github.event.pull_request.merged == true
     runs-on: ubuntu-22.04
     timeout-minutes: 5
@@ -101,9 +101,18 @@ jobs:
         run: |
           set -xeu
 
+          # Fetch tags from the remote to make sure we have the latest tags information
+          git fetch --tags
+
           # Extract the version number from package.json using jq
           version=$(jq -r '.version' package.json)
           echo "Extracted version: $version"
+
+          # Check if the tag already exists
+          if git rev-parse "v${version}" >/dev/null 2>&1; then
+            echo "::error::Tag 'v${version}' already exists. Please update the version number or delete the existing tag."
+            exit 1
+          fi
 
           # Create a new Git tag with the extracted version number
           git tag "v${version}"
